### ISSUE TITLE
About conlleval.pl

### ISSUE THREAD

**Issue by AIRobotZhang** [LeePleased/NegSampling-NER#1]
How can I get the file conlleval.pl？
Thank you!

**Comment by wjx-git** [comment]
conlleval.pl下载地址：
https://www.clips.uantwerpen.be/conll2000/chunking/conlleval.txt

需要安装 activestate 软件，下载地址：
https://www.activestate.com/products/perl/downloads/

需要改动 misc.py 中 f1_score 函数三个地方：
fn_out = 'resource/eval_%04d.txt' % random.randint(0, 10000)
cmd = '%s < %s' % (script_path, fn_out)
if fn_out.startswith('resource/eval_') and os.path.exists(fn_out):
