### ISSUE TITLE
hyperparameter settings for reproducing results

### ISSUE THREAD

**Issue by teffland** [LeePleased/NegSampling-NER#2]
Hi,

Interesting work! I am trying to reproduce your experiments was hoping you could answer a few questions:
* Could you please list any hyperparameter settings/commands you used for the conll2003 and ontonotes5 evaluations?  
* I've found that default batch size is too large and I am getting CUDA OOM issues. What batch size did you use? (My GPU has 16gb ram, so I was  also wondering what the gpu capacity was for the machines used to run the published experiments?)
* For ontonotes, some of the sentences are too long to fit into bert, did you just truncate these?

Thanks!

**Comment by LeePleased** [comment]
Thanks for your attention. 

1) the hyper-parameter settings are available in our paper
2) I used 32GB GPU... (sorry for not considering this). I recommend you to use multi-GPU training
3) yes, I truncated these training cases
